version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:80"
  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
